CREATE PROCEDURE [app].[Jobs_Insert]
	@ScheduleID BIGINT
	,@QueueDateUTC DATETIME2
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
	SET XACT_ABORT, NOCOUNT ON;

	BEGIN TRY
		BEGIN TRANSACTION;

		INSERT INTO [app].[Jobs] (
			[ScheduleID], [QueueDateUTC]
		) VALUES (
			@ScheduleID, @QueueDateUTC
		);

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
		DECLARE @Msg NVARCHAR(2048) = ERROR_MESSAGE();
		RAISERROR(@Msg, 16, 1);
		RETURN 55555;
	END CATCH;
END;
GO
