CREATE TABLE dbo.[Users]
(
    EmailAddress NVARCHAR(200) NOT NULL
    ,CONSTRAINT PK_Users PRIMARY KEY (EmailAddress)

    ,_StartDateTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL
    ,_EndDateTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL
    ,PERIOD FOR SYSTEM_TIME (_StartDateTime, _EndDateTime)
) WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE = dbo.Users_Hist));
GO
